algorithm_description: Create a 1x1 tile of GEDI data
algorithm_name: gedi-tile-writer
algorithm_version: amelia-deploy-HSmHf5Wt
build_command: gedi_tiler/build-env.sh
disk_space: 5GB
docker_container_url: mas.maap-project.org/root/maap-workspaces/base_images/vanilla:v3.1.5
inputs:
  config: []
  positional:
  - default: maap-ops-workspace
    description: AWS bucket in which the GEDI database is stored (e.g. maap-ops-workspace)
    name: bucket
    required: true
  - default: ''
    description: AWS S3 prefix in which the GEDI database is stored (e.g. shared/ameliah/gedi_tiles)
    name: prefix
    required: true
  - default: ''
    description: Tile ID to process. 1x1 degree tiles in the format [N/S][DD][E/W][DDD],
      defining the coordinates of the top-left corner of the tile.
    name: tile_id
    required: true
  - default: 30
    description: Number of granules to process between writing checkpoints.
    name: checkpoint_interval
    required: true
  - default: ''
    description: Quick test running over only 2 GEDI granules.
    name: test
    required: false
  - default: ''
    description: Quality-filter granules before adding to database
    name: quality
    required: false
queue: maap-dps-worker-32gb
repository_url: https://github.com/ameliaholcomb/gedi_tiler.git
run_command: gedi_tiler/run_dps_tile_builder.sh
